#!/bin/bash

# Will need around 200MB free disk space
cd ${OPENSHIFT_REPO_DIR}

MONGODB_VERSION="2.4.8"
MONGODB_PORT=27017
MONGODB_REMOVE_OLD=true # Determine hardware type for pre-compiled linux binary
if [ "`uname -i`" == "x86_64" ]; then
  MONGODB_TYPE="x86_64"
else
  MONGODB_TYPE="i686"
fi

# Prepare Mongodb
if [ ! -e ${OPENSHIFT_DATA_DIR}mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION}/bin/mongod ]; then
  # Delete previous version
  if [ $MONGODB_REMOVE_OLD == "true" ]; then
    echo "rm -rf ${OPENSHIFT_DATA_DIR}mongodb-*"
    rm -rf ${OPENSHIFT_DATA_DIR}mongodb-*
  fi
  cd ${OPENSHIFT_TMP_DIR}
  tarball=''
  if [ "`curl -Is "http://fastdl.mongodb.org/linux/mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION}.tgz" | grep '200 OK'`" != '' ]; then
    tarball="http://fastdl.mongodb.org/linux/mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION}.tgz"
  else
    echo "#### http://fastdl.mongodb.org/linux/mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION}.tgz not exist."
    echo "#### Change mongodb.verion to *2.4.8*"
    MONGODB_VERSION="2.4.8"
    tarball="http://fastdl.mongodb.org/linux/mongodb-linux-${MONGODB_TYPE}-2.4.8.tgz"
  fi
  
  # Download Mongodb
  if [ ! -d mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION} ]; then
    curl -L -o mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION}.tgz $tarball
    tar -xvzf mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION}.tgz
  fi

  # Finalize Mongodb
  mv mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION} ${OPENSHIFT_DATA_DIR}mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION}
  rm -f mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION}.tgz
  mkdir -p ${OPENSHIFT_DATA_DIR}mongodb/data/
  mkdir -p ${OPENSHIFT_DATA_DIR}mongodb/pid/
fi

# Create mongod.conf
cat <<EOF > ${OPENSHIFT_DATA_DIR}mongodb.conf
# mongodb.conf

#where to log
logpath=${OPENSHIFT_DIY_LOG_DIR}mongodb.log

# fork and run in background
fork = true

bind_ip = ${OPENSHIFT_DIY_IP}
port = ${MONGODB_PORT}

dbpath=${OPENSHIFT_DATA_DIR}mongodb/data/

pidfilepath=${OPENSHIFT_DATA_DIR}mongodb/pid/mongodb.pid

# Enables periodic logging of CPU utilization and I/O wait
#cpu = false

# Disable the HTTP interface (Defaults to localhost:27018).
nohttpinterface = true

# Disable journal to save disk space
nojournal = true

# Disable data file preallocation.
noprealloc = true
EOF

# Create a shell script to start mongo shell
cat <<EOF > ${OPENSHIFT_DATA_DIR}/mongo_shell.sh
${OPENSHIFT_DATA_DIR}mongodb-linux-${MONGODB_TYPE}-${MONGODB_VERSION}/bin/mongo --host ${OPENSHIFT_DIY_IP} --port ${MONGODB_PORT}
EOF
chmod +x ${OPENSHIFT_DATA_DIR}/mongo_shell.sh

# Create environment variables for this version
cat <<EOF > ${OPENSHIFT_DATA_DIR}/node.sh
export MONGODB_VERSION=${MONGODB_VERSION}
export MONGODB_TYPE=${MONGODB_TYPE}
export MONGODB_PORT=${MONGODB_PORT}
export MONGODB_URL=mongodb://${OPENSHIFT_DIY_IP}:${MONGODB_PORT}/
export TMPDIR=\${OPENSHIFT_TMP_DIR}

EOF

