#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
cd ${OPENSHIFT_REPO_DIR}
# Backup server.log if exist
BACKUP_LOG=${OPENSHIFT_DIY_LOG_DIR}backup_log
LOG_FILE=${OPENSHIFT_DIY_LOG_DIR}server.log

# Backup mongodb.log if exist
MONGODB_LOG_FILE=${OPENSHIFT_DIY_LOG_DIR}mongodb.log
if [ -s $MONGODB_LOG_FILE ]; then
  # Get the modify time of the log file
  MODIFY=`stat -c "%Y" $MONGODB_LOG_FILE`
  # Convert to time stamp
  STAMP=`date -d @$MODIFY "+%Y%m%d-%H%M%S"`
  mv -f $MONGODB_LOG_FILE ${BACKUP_LOG}/mongodb.log.${STAMP}
fi

# Start Mongodb server
mongod --config ${OPENSHIFT_DATA_DIR}mongodb.conf --replSet rs0 