#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

cd ${OPENSHIFT_REPO_DIR}
# Backup server.log if exist
BACKUP_LOG=${OPENSHIFT_DIY_LOG_DIR}backup_log
LOG_FILE=${OPENSHIFT_DIY_LOG_DIR}server.log

# Start Mongodb server
mongod --config ${OPENSHIFT_DATA_DIR}mongodb.conf --replSet rs0 