#!/bin/bash
# Stop Mongodb
PIDFILE=${OPENSHIFT_DATA_DIR}mongodb/pid/mongodb.pid
if [ ! -f $PIDFILE ]; then
        echo "$PIDFILE does not exist, mongodb is not running"
else
        PID=$(cat $PIDFILE)
        echo "Stopping MongoDB..."
        mongod --config ${OPENSHIFT_DATA_DIR}mongodb.conf --shutdown
        while [ -x /proc/${PID} ]
        do
            echo "Waiting for MongoDB to shutdown ..."
            sleep 1
        done
        echo "MongoDB stopped"
fi